name: observatory-crate-workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */6 *"
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      ROCRATE_PROFILE_URI: undefined
      WATER_LOGSHEET_URL: undefined
      SEDIMENT_LOGSHEET_URL: undefined
      HARD_LOGSHEET_URL: undefined
      DATA_QUALITY_CONTROL_THRESHOLD_DATE: "2100-01-01"
      DATA_QUALITY_CONTROL_ASSIGNEE: github-actions[bot]
      RDF_AGGREGATOR_GLOB: "sediment/**/*: ttl, water/**/*: ttl, ro-crate-metadata.json: json-ld"
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: populate-action
        uses: emo-bon/populate-action@main
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: update on behalf of populate-action
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: update on behalf of data-quality-control-action
      - name: semantic-uplifting-action
        uses: emo-bon/semantic-uplifting-action@main
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update on behalf of semantic-uplifting-action
      - name: rocrate-to-pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
        with:
          multiple_rocrates: true
          release_management: false
          include_draft: false
          index_html: false
          space_to_pages_homepage: https://data.emobon.embrc.eu
      - name: actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
